# 头部菜单，title: link
menu:
  About: /about
  Github: https://github.com/luxutao
  Twitter: https://twitter.com/luxutao

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: /
    wechat: /img/logo.png
    email: mailto:xxxx@gmail.com

# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://music.163.com/song/media/outer/url?id=532940065.mp3
  - http://music.163.com/song/media/outer/url?id=532940065.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: false

# 是否显示 一言(hitokoto)
hitokoto: true

# 是否使用mathjax
mathjax: false

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '0466599dee5443f20cd2'
    # 应用秘钥
    clientSecret: '7d7e365bd03dffdeaeccd0461b769b01f707bd10'
    # issue仓库名
    repo: 'comment'
    # Github名
    owner: 'luxutao'
    # Github名
    admin: ['luxutao']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: luxutao

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
