# 头部菜单，title: link
menu:
  About: /about
  Github: https://github.com/luxutao
  Twitter: https://twitter.com/luxutao

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - https://pan.animekid.cn/f/8892a4af1e4a4e00b849/?dl=1
  - https://pan.animekid.cn/f/eb1309a52ed94cb58f8a/?dl=1

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '0466599dee5443f20cd2'
    # 应用秘钥
    clientSecret: '7d7e365bd03dffdeaeccd0461b769b01f707bd10'
    # issue仓库名
    repo: 'comment'
    # Github名
    owner: 'luxutao'
    # Github名
    admin: ['luxutao']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: luxutao

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
